In [1]:
import tabula
import pandas as pd
import numpy as np
import os
import re
  
folder_path = 'pdfs/data2'

# Create an empty list to hold the file names or paths
pdfs = []

# Loop through each file in the folder
for file_name in os.listdir(folder_path):
    # Check if the file is a PDF file
    if file_name.endswith('.pdf'):
        # Add the file name or path to the list
        file_path = os.path.join(folder_path, file_name)
        pdfs.append(file_path)  # Change to `file_name` to get only the file name instead of the full path

In [2]:
dfs = []
for f in pdfs:
    # Use Tabula to extract pages with tables
    df = tabula.read_pdf(f, pages='all')[0]
    dfs.append(df)

In [3]:
#check columns' names for each dataframe in the list of dataframes
for df in dfs:
    print(df.columns)

Index(['Under', '$50K-', '$60K-', '$70K-'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Report Information', 'Unnamed: 0'], dtype='object')
Index(['Under', '$50K-', '$60K-', '$70K-', '$80K-', 'Over'], dtype='object')
Index(['Report Information', 'Unnamed: 0'], dtype='object')
Index(['AllenrolledstudentswhowereincludedintheCIRROutcomesReport\rexistandareaccurately reportedin accordancewith Council on Integrity\rin Results Reporting ("CIRR") Standards & Implementation Requirements\rrev.2020-07-07whichgovernsoutcomereportingforgraduatesduring\r2021.Including,studentsthatwereenrolledduringthereporting period\rand included in the underlying data used for reporting results of the CIRR\rOutcomes Report.',
       'Existence and\rAccuracy',
       'AGLCPA Group,LLC("AGL") will obtain frommanagement alist ofstudents who\rare designatedas enrolled,per thepublished CIRRStandards,intheprogramfor the\rsix-monthperiodfromJanuary1,2021throughJune30,2021,andperformthe\rfollowing procedures to test existence and accuracy.'],
      dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2'], dtype='object')
Index(['Report Information', 'Unnamed: 0'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Report Information', 'Unnamed: 0'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['AllenrolledstudentswhowereincludedintheCIRROutcomesReport\rexistandareaccurately reportedin accordancewith Council on Integrity\rin Results Reporting ("CIRR") Standards & Implementation Requirements\rrev.2020-07-07whichgovernsoutcomereportingforgraduatesduring\r2020; including students that were enrolled during the reporting period and\rincludedintheunderlyingdatausedforreportingresultsoftheCIRR\rOutcomes Report.',
       'Existence and\rAccuracy',
       'AGL CPA Group, LLC ("AGL") will obtain from management a list of students who are\rdesignatedasenrolled,perthepublishedCIRRStandards,intheprogramforthesix-\rmonthperiodsJanuary1,2020throughJune30,2020andJuly1,2020through\rDecember31,2020,andperformthefollowingprocedurestotestexistenceand\raccuracy.'],
      dtype='object')
Index(['Under', '$40K-', '$50K-', '$60K-', 'Over'], dtype='object')
Index(['AllenrolledstudentswhowereincludedintheCIRROutcomesReport\rexistandareaccurately reportedin accordancewith Council on Integrity\rin Results Reporting ("CIRR") Standards & Implementation Requirements\rrev.2020-07-07whichgovernsoutcomereportingforgraduatesduring\r2020; including students that were enrolled during the reporting period and\rincludedintheunderlyingdatausedforreportingresultsoftheCIRR\rOutcomes Report.',
       'Existence and\rAccuracy',
       'AGL CPA Group, LLC ("AGL") will obtain from management a list of students who are\rdesignatedasenrolled,perthepublishedCIRRStandards,intheprogramforthesix-\rmonthperiodJuly1,2020throughDecember31,2020,andperformthefollowing\rprocedures to test existence and accuracy.'],
      dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['AllenrolledstudentswhowereincludedintheCIRROutcomesReport\rexistandareaccurately reportedin accordancewith Council on Integrity\rin Results Reporting ("CIRR") Standards & Implementation Requirements\rrev.2020-07-07whichgovernsoutcomereportingforgraduatesduring\r2020; including students that were enrolled during the reporting period and\rincludedintheunderlyingdatausedforreportingresultsoftheCIRR\rOutcomes Report.',
       'Existence and\rAccuracy',
       'AGL CPA Group, LLC ("AGL") will obtain from management a list of students who are\rdesignatedasenrolled,perthepublishedCIRRStandards,intheprogramforthesix-\rmonthperiodJanuary1,2020throughJune30,2020,andperformthefollowing\rprocedures to test existence and accuracy.'],
      dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Report Information', 'Unnamed: 0'], dtype='object')
Index(['Report Information', 'Unnamed: 0'], dtype='object')
Index(['Report Information', 'Unnamed: 0'], dtype='object')
Index(['Report Information', 'Unnamed: 0'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Under', '$50K-', '$60K-', '$80K-', 'Over'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['AllenrolledstudentswhowereincludedintheCIRROutcomesReport\rexistandareaccurately reportedin accordancewith Council on Integrity\rin Results Reporting ("CIRR") Standards & Implementation Requirements\rrev.2020-07-07whichgovernsoutcomereportingforgraduatesduring\r2020; including students that were enrolled during the reporting period and\rincludedintheunderlyingdatausedforreportingresultsoftheCIRR\rOutcomes Report.',
       'Existence and\rAccuracy',
       'AGL CPA Group, LLC ("AGL") will obtain from management a list of students who are\rdesignatedasenrolled,perthepublishedCIRRStandards,intheprogramforthesix-\rmonthperiodsJanuary1,2020throughJune30,2020andJuly1,2020through\rDecember31,2020,andperformthefollowingprocedurestotestexistenceand\raccuracy.'],
      dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Report Information', 'Unnamed: 0'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Report Information', 'Unnamed: 0'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Report Information', 'Unnamed: 0'], dtype='object')
Index(['Under', '$90K -', '$100K -', '$110K -', '$120K -', 'Over'], dtype='object')
Index(['Report Information', 'Unnamed: 0'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['AllenrolledstudentswhowereincludedintheCIRROutcomesReport\rexistandareaccurately reportedin accordancewith Council on Integrity\rin Results Reporting ("CIRR") Standards & Implementation Requirements\rrev.2020-07-07whichgovernsoutcomereportingforgraduatesduring\r2020.Including,studentsthatwereenrolledduringthereporting period\rand included in the underlying data used for reporting results of the CIRR\rOutcomes Report.',
       'Existence and\rAccuracy',
       'AGLCPA Group,LLC("AGL") will obtain frommanagement alist ofstudents who\rare designatedas enrolled,per thepublished CIRRStandards,intheprogramfor the\rsix-monthperiodfromJuly1,2020throughDecember31,2020,andperformthe\rfollowing procedures to test existence and accuracy.'],
      dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Under', '$70K -', '$80K -'], dtype='object')
Index(['Report Information', 'Unnamed: 0'], dtype='object')
Index(['AllenrolledstudentswhowereincludedintheCIRROutcomesReport\rexistandareaccurately reportedin accordancewith Council on Integrity\rin Results Reporting ("CIRR") Standards & Implementation Requirements\rrev.2020-07-07whichgovernsoutcomereportingforgraduatesduring\r2020; including students that were enrolled during the reporting period and\rincludedintheunderlyingdatausedforreportingresultsoftheCIRR\rOutcomes Report.',
       'Existence and\rAccuracy',
       'AGL CPA Group, LLC ("AGL") will obtain from management a list of students who are\rdesignatedasenrolled,perthepublishedCIRRStandards,intheprogramforthesix-\rmonthperiodsJanuary1,2020throughJune30,2020andJuly1,2020through\rDecember31,2020,andperformthefollowingprocedurestotestexistenceand\raccuracy.'],
      dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['b)', 'Ensuring that reported figures on spreadsheets used to build the CIRR report conform to'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['Report Information', 'Unnamed: 0'], dtype='object')
Index(['What median pay rate do graduates earn?  $62,750\rK\r180 Days After Completion\r-$50\r40$K\rUnder$50K-$70K-Over\r$40K\r$60K$80K$80K\r22.2%0.0% 11.1% 0.0%\r22.2%44.4%\rWhat percentage of job obtainers reported salaries?\r81.8%',
       'Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],
      dtype='object')
Index(['Report Information', 'Unnamed: 0'], dtype='object')
Index(['Report Information', 'Unnamed: 0'], dtype='object')
Index(['Under', '$60K -', '$70K -', '$70K -.1'], dtype='object')
Index(['Report Information', 'Unnamed: 0'], dtype='object')
Index(['Report Information', 'Unnamed: 0'], dtype='object')
Index(['Report Information', 'Unnamed: 0'], dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['AllenrolledstudentswhowereincludedintheCIRROutcomesReport\rexistandareaccurately reportedin accordancewith Council on Integrity\rin Results Reporting ("CIRR") Standards & Implementation Requirements\rrev.2020-07-07whichgovernsoutcomereportingforgraduatesduring\r2020; including students that were enrolled during the reporting period and\rincludedintheunderlyingdatausedforreportingresultsoftheCIRR\rOutcomes Report.',
       'Existence and\rAccuracy',
       'AGL CPA Group, LLC ("AGL") will obtain from management a list of students who are\rdesignatedasenrolled,perthepublishedCIRRStandards,intheprogramforthesix-\rmonthperiodsJanuary1,2020throughJune30,2020andJuly1,2020through\rDecember31,2020,andperformthefollowingprocedurestotestexistenceand\raccuracy.'],
      dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')
Index(['AllenrolledstudentswhowereincludedintheCIRROutcomesReport\rexistandareaccurately reportedin accordancewith Council on Integrity\rin Results Reporting ("CIRR") Standards & Implementation Requirements\rrev.2020-07-07whichgovernsoutcomereportingforgraduatesduring\r2020; including students that were enrolled during the reporting period and\rincludedintheunderlyingdatausedforreportingresultsoftheCIRR\rOutcomes Report.',
       'Existence and\rAccuracy',
       'AGL CPA Group, LLC ("AGL") will obtain from management a list of students who are\rdesignatedasenrolled,perthepublishedCIRRStandards,intheprogramforthesix-\rmonthperiodsJanuary1,2020throughJune30,2020andJuly1,2020through\rDecember31,2020,andperformthefollowingprocedurestotestexistenceand\raccuracy.'],
      dtype='object')
Index(['Report Information', 'Unnamed: 0', 'Unnamed: 1'], dtype='object')

We are only interested in data frames with columns 'Report Information', 'Unnamed: 0', 'Unnamed: 1' or
'Report Information', 'Unnamed: 0'

In [4]:
dfs[21]

,"AllenrolledstudentswhowereincludedintheCIRROutcomesReport\rexistandareaccurately reportedin accordancewith Council on Integrity\rin Results Reporting (""CIRR"") Standards & Implementation Requirements\rrev.2020-07-07whichgovernsoutcomereportingforgraduatesduring\r2020; including students that were enrolled during the reporting period and\rincludedintheunderlyingdatausedforreportingresultsoftheCIRR\rOutcomes Report.",Existence and\rAccuracy,"AGL CPA Group, LLC (""AGL"") will obtain from management a list of students who are\rdesignatedasenrolled,perthepublishedCIRRStandards,intheprogramforthesix-\rmonthperiodJuly1,2020throughDecember31,2020,andperformthefollowing\rprocedures to test existence and accuracy."
0,NaN,1) AGL will verify enrollment with the student...,NaN
1,Enrolledstudentswhowereenrolledintheprogramexi...,"Existence,\rClassification and\rAccuracy",2)AGLwillverifygraduationdatewiththestudentthr...
2,Enrolled students who were enrolled in the pro...,"Existence,\rClassification and\rAccuracy",3)AGLwill verifythestudentwasemployedasstatedi...
3,"Graduatesreportedsalary'safteremploymentexist,...","Existence,\rClassification and\rAccuracy",4)AGLwillverifythestudent'ssalaryasstatedinthe...

In [5]:
#pick the right dataframes
#only the dataframes that have 'Report Information' column
col_name = 'Report Information'
new_df = []
for df in dfs:
    if col_name not in df.columns:
        continue
    new_df.append(df)

In [6]:
new_df[21]

                                   Report Information               Unnamed: 0
0                                         School Name         The Tech Academy
1                                     Campus Location                   Online
2                                                 NaN  Software Developer Boot
3                                        Program Name                      NaN
4                                                 NaN                     Camp
5                                    Reporting Period      7/1/2021 12/31/2021
6   Published Course Length (in days, including we...               Self-paced
7                        Graduates Included in Report                       46
8                             Graduation Requirements                      NaN
9                       - Complete all course modules                      NaN
10                           - Complete final project                      NaN
11                                    Graduation Data                      NaN
12                          Median days to graduation                      190
13                                    Graduation Rate                    61.5%
14                                       < 129.5 days                     2.6%
15                                   129.5-159.5 days                     3.8%
16                                   159.5-189.5 days                    19.2%
17                                   189.5-219.5 days                    11.5%
18                                   219.5-249.5 days                     6.4%
19                                        249.5+ days                    17.9%
20            Still enrolled as of reporting end date                     2.6%
21                                           Withdrew                    35.9%
22                                        Job Seekers                      NaN
23  How many students intended to seek in-field em...                    95.8%
24  How many students did not intend to seek in-fi...                      NaN
25  employer, no work authorization, continuing to...                     4.2%
26                                 Employment Results         90 days 180 days
27                               1. Employed in-field              50.0% 63.0%
28  1A. Full-time employee (30+ hours/week, 6+ mon...              47.8% 58.7%
29  1B. Full-time apprenticeship, internship, or c...                0.0% 0.0%
30  1C. Short-term contract, part-time position, f...                2.2% 4.3%
31  1D. Started a new company or venture after gra...                0.0% 0.0%
32                 2. Not seeking in-field employment                6.5% 6.5%
33                          2A. Employed out-of-field                2.2% 2.2%
34                 2B. Continuing to higher education                0.0% 0.0%
35  2C. Not seeking a job for health, family, or p...                4.3% 4.3%
36                    3. Still seeking a job in-field              34.8% 21.7%
37                               4. Could not contact                8.7% 8.7%
38                                    Hired by School                4.3% 4.3%
39                          Median Annual Base Salary          $45,760 $57,000
40                                      Under $40,000              17.6% 17.4%
41                                    $40,000-$50,000              23.5% 26.1%
42                                    $50,000-$60,000               11.8% 8.7%
43                                    $60,000-$70,000              23.5% 26.1%
44                                    $70,000-$80,000                5.9% 4.3%
45                                       Over $80,000              17.6% 17.4%
46  Percentage of job obtainers who reported salaries              73.9% 76.7%
47                           Most Frequent Job TItles                      NaN
48                                 Software Developer                    25.8%
49                                    Project Manager                    22.6%
50                                  Software Engineer                    12.9%
51                                      Web Developer                     9.7%
52                                          Developer                     9.7%

In [7]:
for df in new_df:
    if 'Unnamed: 1' in df.columns:
        df['Unnamed: 0'] = df['Unnamed: 0'].fillna('') + ' ' + df['Unnamed: 1'].fillna('')
        df.drop('Unnamed: 1', inplace=True, axis=1)

In [8]:
for i in range(0, len(new_df)):
    if 'Unnamed: 2' in new_df[i].columns:
        new_df[i].drop('Unnamed: 2', axis=1, inplace=True)

In [9]:
nums_toshift = [2,19,38,44]
for n in nums_toshift:
    new_df[n].loc[0, :] = new_df[n].loc[0, :].fillna('') +' '+ new_df[n].loc[1, :].fillna('')
    new_df[n] = new_df[n].drop(1)

In [10]:
nums_toshift = [21,46,47,49]
for n in nums_toshift:
    if pd.isna(new_df[n].loc[2, 'Report Information']):
        new_df[n].loc[2,'Report Information'] = new_df[n].loc[3, 'Report Information']
        new_df[n].loc[2, 'Unnamed: 0'] = str(new_df[n].loc[2, 'Unnamed: 0']) + '' + str(new_df[n].loc[3, 'Unnamed: 0'])
    else:
        new_df[n].loc[2,'Report Information'] += new_df[n].loc[3, 'Report Information']
        new_df[n].loc[2, 'Unnamed: 0'] = str(new_df[n].loc[2, 'Unnamed: 0']) + ' ' + str(new_df[n].loc[3, 'Unnamed: 0'])
    new_df[n] = new_df[n].drop(3)

In [11]:
#filter out all the rows containing 'days' substring in 'Report Information' column
# we are only interested in graduation rate
string_filter = 'days'
col_name = 'Report Information'
for i in range(0,len(new_df)):
    #replace NaN with empty string in order to use str.contains
    new_df[i] = new_df[i][new_df[i][col_name].str.endswith(string_filter) == False]

In [12]:
substring = 'obtainers'
col_name = 'Report Information'
df2 = []
#create a regular expression to igonre case for the string I'm looking for
regex = re.compile(substring,re.IGNORECASE)
for i in range(0,len(new_df)):
    mask = new_df[i][col_name].apply(lambda x: bool(regex.search(str(x))))  # Create a boolean mask to filter rows containing the substring
    ind = new_df[i].loc[mask].index[0]  # Get the index of the first row containing the substring 
    new_df[i] = new_df[i].loc[:ind-1]

In [13]:
#remove all rows that start with -, * or combination of digit and character
col_name = 'Report Information'
regex = re.compile(r'^([0-9][a-zA-Z]|[\\*\\-])')
for i in range(0,len(new_df)):
    mask = new_df[i][col_name].str.extract(regex).notnull().any(axis=1) # create a boolean mask
    new_df[i] = new_df[i][~mask]

In [14]:
new_df[21]

,Report Information,Unnamed: 0
0,School Name,The Tech Academy
1,Campus Location,Online
2,Program Name,Software Developer Bootnan
5,Reporting Period,7/1/2021 12/31/2021
6,"Published Course Length (in days, including we...",Self-paced
7,Graduates Included in Report,46
8,Graduation Requirements,NaN
11,Graduation Data,NaN
12,Median days to graduation,190
13,Graduation Rate,61.5%
20,Still enrolled as of reporting end date,2.6%
21,Withdrew,35.9%
22,Job Seekers,NaN
23,How many students intended to seek in-field em...,95.8%
24,How many students did not intend to seek in-fi...,NaN
25,"employer, no work authorization, continuing to...",4.2%
26,Employment Results,90 days 180 days
27,1. Employed in-field,50.0% 63.0%
32,2. Not seeking in-field employment,6.5% 6.5%
36,3. Still seeking a job in-field,34.8% 21.7%
37,4. Could not contact,8.7% 8.7%
38,Hired by School,4.3% 4.3%
39,Median Annual Base Salary,"$45,760 $57,000"
40,"Under $40,000",17.6% 17.4%
41,"$40,000-$50,000",23.5% 26.1%
42,"$50,000-$60,000",11.8% 8.7%
43,"$60,000-$70,000",23.5% 26.1%
44,"$70,000-$80,000",5.9% 4.3%
45,"Over $80,000",17.6% 17.4%

In [15]:
#transpose each dataframe, if the collumns appear null, change to 'col'
#select first row for columns names
new2 = []
for df in new_df:
    df = df.transpose()
    cols = df.iloc[0]
    cols.fillna('col', inplace=True)
    df.columns = cols
    df = df[1:]
    new2.append(df)

In [16]:
for df in new2:
    s = df.columns.to_series().groupby(df.columns)
    df.columns = np.where(s.transform('size')>1, 
                      df.columns + s.cumcount().add(1).astype(str), 
                      df.columns)

In [17]:
new2[21]

,School Name,Campus Location,Program Name,Reporting Period,"Published Course Length (in days, including weekends and holidays)",Graduates Included in Report,Graduation Requirements,Graduation Data,Median days to graduation,Graduation Rate,...,3. Still seeking a job in-field,4. Could not contact,Hired by School,Median Annual Base Salary,"Under $40,000","$40,000-$50,000","$50,000-$60,000","$60,000-$70,000","$70,000-$80,000","Over $80,000"
Unnamed: 0,The Tech Academy,Online,Software Developer Bootnan,7/1/2021 12/31/2021,Self-paced,46,NaN,NaN,190,61.5%,...,34.8% 21.7%,8.7% 8.7%,4.3% 4.3%,"$45,760 $57,000",17.6% 17.4%,23.5% 26.1%,11.8% 8.7%,23.5% 26.1%,5.9% 4.3%,17.6% 17.4%

In [18]:
#before combining all dataframes into one drop all the columns, that only contain null values
for i, df in enumerate(new2):
    null_columns = df.columns[df.isnull().all()].tolist()
    if len(null_columns) > 0:
        new2[i] = df.drop(null_columns, axis=1)

In [19]:
final = pd.concat(new2)
final = final.reset_index().drop(columns=['index'])

In [20]:
cols_to_drop = ['Graduation Requirements','Graduation Data','Median days to graduation','Still enrolled as of reporting end date', 'Withdrew', 'Job Seekers',
       'How many students did not intend to seek in-field employment (returning to previous\remployer, no work authorization, continuing to further education, or self-enrichment)?',
       'Employment Results','4. Could not contact',
       'Hired by School',
       'How many students graduate within 150% of published program length?',
        'employer, no work authorization, continuing to further education, or self-enrichment)?',
        'Could not contact','How many students did not intend to seek in-field employment (returning to previous employer,\rno work authorization, continuing to further education, or self-enrichment)?',
        'authorization, continuing to further education, or self-enrichment)?',
        'How many students graduate within 150% of published program length',
        'How many students did not intend to seek in-field employment (returning to previous employer, no work\rauthorization, continuing to further education, or self enrichment)?',
        'authorization, continuing to further education, or self-enrichment)?',
        'Median Days to Graduation'
        
        
       ]
final = final.drop(cols_to_drop, axis=1)

In [21]:
# we see tha we have 2 'School Name', one contains traling space, we need to combine these two columns
# we also need to combine 'Graduation Rate' and 'How many students graduate within 100% of published program length (on-time)?'
final.columns

Index(['School Name', 'Campus Location', 'Program Name', 'Reporting Period',
       'Published Course Length (in days, including weekends and holidays)',
       'Graduates Included in Report', 'Graduation Rate',
       'How many students intended to seek in-field employment within 180 days of graduating?',
       '1. Employed in-field', '2. Not seeking in-field employment',
       '3. Still seeking a job in-field', 'Median Annual Base Salary',
       'Under $60,000', '$60,000-$70,000', '$70,000-$80,000',
       '$80,000-$90,000', '$90,000-$100,000', 'Over $100,000', 'Under $40,000',
       '$40,000-$50,000', '$50,000-$60,000', 'Over $80,000', ' School Name',
       'How many students graduate within 100% of published program length (on-time)?',
       'Under $70,000', '$100,000-$110,000', 'Over $110,000', 'Under $50,000',
       'Over $90,000', 'Under $80,000', '$110,000-$120,000', 'Over $120,000',
       '1. Employed In-Field',
       'What is the median annual base salary of graduates?', 'Under $110,000',
       '$120,000-$130,000', '$130,000-$140,000', '$140,000-$150,000',
       'Over $150,000', '$60,000-70,000', '$70,000-80,000', '$80,000-90,000',
       'Under $30,000', '$30,000-$40,000', 'Over $70,000', 'Under $100,000',
       'Over $140,000',
       'What is the median annual base salary of graduates?        US Dollar Annual Salary',
       'Under $120,000', '$150,000-$160,000', 'Over $160,000',
       'How many students intended to seek in-field employment within 180 days of graduating'],
      dtype='object')

In [22]:
final['School Name'] = final['School Name'].fillna('') + ' ' + final[' School Name'].fillna('')
final.drop(' School Name', inplace=True, axis=1)

In [23]:

final['Graduation Rate'] = final['Graduation Rate'].fillna('') + ' ' + final['How many students graduate within 100% of published program length (on-time)?'].fillna('')
final.drop('How many students graduate within 100% of published program length (on-time)?', inplace=True, axis=1)

In [24]:

final['Median Annual Base Salary'] = final['Median Annual Base Salary'].fillna('') + final['What is the median annual base salary of graduates?        US Dollar Annual Salary'].fillna('') + final['What is the median annual base salary of graduates?'].fillna('')
final.drop('What is the median annual base salary of graduates?        US Dollar Annual Salary', inplace=True, axis=1)
final.drop('What is the median annual base salary of graduates?', inplace=True, axis=1)

In [25]:
final['1. Employed in-field'] = final['1. Employed in-field'].fillna('')  + final['1. Employed In-Field'].fillna('')
final.drop('1. Employed In-Field', inplace=True, axis=1)

In [26]:
final

,School Name,Campus Location,Program Name,Reporting Period,"Published Course Length (in days, including weekends and holidays)",Graduates Included in Report,Graduation Rate,How many students intended to seek in-field employment within 180 days of graduating?,1. Employed in-field,2. Not seeking in-field employment,...,"$80,000-90,000","Under $30,000","$30,000-$40,000","Over $70,000","Under $100,000","Over $140,000","Under $120,000","$150,000-$160,000","Over $160,000",How many students intended to seek in-field employment within 180 days of graduating
0,The Tech Academy,Online,Python Developer Boot Camp,7/1/2021 12/31/2021,Self-paced,9,82.4%,90.0%,55.6% 66.7%,11.1% 11.1%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,The Tech Academy,Online,Data Science Boot Camp,1/1/2021 6/30/2021,Self-paced,3,100.0%,100.0%,66.7% 100.0%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Turing School of Software and Design,Online,Back End Engineering,1/1/2021 6/30/2021,220,84,68.0%,100.0%,64.3% 76.2%,2.4% 2.4%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Codeup,Dallas,Full-Stack Web Development,1/1/2021 6/30/2021,200,14,82.4%,100.0%,50.0% 92.9%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Code Platoon,Chicago,Full-Stack Web Development,7/1/2021 12/31/2021,120,16,81.0%,94.1%,62.5% 81.3%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Tech Elevator,Pittsburgh,Full-Stack Software Development,1/1/2021 6/30/2021,95,42,95.5%,100.0%,66.7% 90.4%,2.4% 4.8%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Codeup,San Antonio,Data Science,7/1/2021 12/31/2021,200,42,85.7%,100.0%,78.6% 88.1%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,"Codeup, LLC",San Antonio,Data Science,7/1/2020 12/21/2020,165,16,94.1%,100.0%,43.8% 81.3%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Code Platoon,Chicago,Full-Stack Web Development,7/1/2020 12/31/2020,104,15,88.2%,93.3%,46.7% 60.0%,6.7% 6.7%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Codesmith,Los Angeles,Full-Stack Web Development,1/1/2021 6/30/2021,100,130,94.8%,99.2%,48.1% 85.3%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Tech Elevator,National Live Remote,Full-Stack Software Development,1/1/2021 6/30/2021,95,59,88.1%,79.7%,61.0% 89.8%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Tech Elevator,Cleveland,Full-Stack Software Development,1/1/2021 6/30/2021,95,31,94.7%,86.1%,74.2% 83.9%,0.0% 0.0%,...,0.0% 0.0%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Tech Elevator,Columbus,Full-Stack Software Development,7/1/2021 12/31/2021,95,116,95.2%,98.3%,85.3% 94.0%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Codeup,San Antonio,Full-Stack Web Development,7/1/2021 12/31/2021,200,81,86.2%,100.0%,58.0% 81.5%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,"Codeup, LLC",San Antonio,Full-Stack Web Development\r- Java -,7/1/2020 12/31/2020,170,38,80.9%,100.0%,36.8% 63.2%,0.0% 2.6%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Tech Elevator,Cincinnati,Full-Stack Software Development,7/1/2021 12/31/2021,95,64,95.5%,100.0%,87.5% 93.7%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Code Platoon,Chicago,Full-Stack Web Development,7/1/2021 12/31/2021,220,12,85.7%,100.0%,58.3% 83.3%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Codesmith,West Coast Remote,Full-Stack Web Development,7/1/2021 12/31/2021,100,110,91.9%,94.0%,40.0% 80.9%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Tech Elevator,Philadelphia,Full-Stack Software Development,7/1/2021 12/31/2021,95,58,93.5%,100.0%,63.8% 86.2%,3.4% 3.4%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Turing School of Software and Design,Online,Front End Engineering,1/1/2021 6/30/2021,220,85,72.3%,100.0%,58.8% 70.6%,3.5% 3.5%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Juno College of Technology,Toronto,Web Development Immersive,7/1/2021 12/31/2021,77,110,95.8%,99.0%,37.1% 70.1%,5.2% 6.2%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,The Tech Academy,Online,Software Developer Bootnan,7/1/2021 12/31/2021,Self-paced,46,61.5%,95.8%,50.0% 63.0%,6.5% 6.5%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,The Tech Academy,Online,Boot Camp,1/1/2021 6/30/2021,Self-paced,14,90.9%,93.3%,57.1% 78.6%,14.3% 14.3%,...,NaN,33.3% 33.3%,33.3% 33.3%,0.0% 0.0%,NaN,NaN,NaN,NaN,NaN,NaN
23,Codesmith,New York,Full-Stack Web Development,1/1/2021 6/30/2021,100,123,94.7%,96.9%,51.2% 89.4%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,15.9% 12.3%,19.0% 17.9%,NaN,NaN,NaN,NaN
24,The Tech Academy,"Salt Lake City, Utah",Software Developer Bootcamp,7/1/2020 12/31/2020,Self-paced,10,90.9%,100.0%,50.0% 50.0%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Tech Elevator,National Live Remote,Full-Stack Software Development,7/1/2021 12/31/2021,95,93,88.6%,100.0%,66.7% 89.2%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Tech Elevator,Cleveland,Full-Stack Software Development,7/1/2021 12/31/2021,95,73,96.7%,83.0%,93.2% 94.5%,0.0% 1.4%,...,8.8% 8.7%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Tech Elevator,Columbus,Full-Stack Software Development,1/1/2021 6/30/2021,95,47,96.3%,90.4%,85.1% 93.6%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Code Chrysalis,"Tokyo, Japan",The Immersive Bootcamp,7/1/2020 12/31/2020,84,40,93.0%,88.9%,52.5% 72.5%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Codeup,San Antonio - Vogue,Full-Stack Web Development,1/1/2021 6/30/2021,200,66,75.0%,100.0%,59.1% 84.8%,1.5% 1.5%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,"Codeup, LLC",Dallas,Full-Stack Web Development-Java,7/1/2020 12/21/2020,170,17,100.0%,100.0%,50.0% 75.0%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Tech Elevator,Cincinnati,Full-Stack Software Development,1/1/2021 6/30/2021,95,34,89.7%,97.1%,64.8% 76.5%,5.8% 8.8%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Codeup,Dallas,Full-Stack Web Development,7/1/2021 12/31/2021,200,17,89.5%,100.0%,58.8% 82.4%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Code Platoon,Chicago,Full-Stack Web Development,1/1/2021 6/30/2021,120,55,91.8%,98.2%,64.2% 84.9%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Launch Academy,Boston,Fundamentals of Web Development,7/1/2021 12/31/2021,90,15,57.7%,93.3%,64.3% 92.9%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Codeup,San Antonio - Vogue,Data Science,1/1/2021 6/30/2021,200,36,94.7%,100.0%,63.9% 86.1%,2.8% 2.8%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Tech Elevator,Pittsburgh,Full-Stack Software Development,7/1/2021 12/31/2021,95,100,95.2%,100.0%,84.0% 91.0%,3.0% 3.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Codesmith,Central Remote Immersive,Full-Stack Web Development,7/1/2021 12/31/2021,100,62,95.7%,93.9%,46.8% 82.3%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,24.0% 23.4%,8.0% 4.3%,24.0% 14.9%,NaN
38,Turing School of Software and Design,Online,Back End Engineering,7/1/2021 12/31/2021,220,47,48.1%,100.0%,55.4% 78.6%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Codesmith,East Coast Remote,Full-Stack Web Development,7/1/2021 12/31/2021,100,91,92.8%,NaN,52.7% 83.5%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,12.5% 15.4%,2.5% 1.5%,25.0% 24.6%,96.8%
40,The Tech Academy,Online,Python Developer Boot Camp,1/1/2021 6/30/2021,Self-paced,16,78.3%,100.0%,56.3% 68.8%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,The Tech Academy,Online,C# and .NET Boot Camp,1/1/2021 6/30/2021,Self-paced,33,57.1%,97.1%,51.5% 60.6%,12.1% 15.2%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Codesmith,Remote,Part-Time Full-Stack Web\rDevelopment,1/1/2021 6/30/2021,270,25,100.0%,89.3%,70.8% 87.5%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,14.3% 19.0%,28.6% 23.8%,NaN,NaN,NaN,NaN
43,Tech Elevator,Philadelphia,Full-Stack Software Development,1/1/2021 6/30/2021,95,23,88.5%,100.0%,69.6% 91.3%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Turing School of Software and Design,Online,Front End Engineering,7/1/2021 12/31/2021,220,59,74.4%,100.0%,72.3% 84.6%,1.5% 1.5%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Juno College of Technology,Toronto,Web Development Immersive,1/1/2021 6/30/2021,77,123,94.0%,100.0%,59.3% 79.7%,1.6% 2.4%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,The Tech Academy,Online,Software Developer BootCamp,1/1/2021 6/30/2021,Self-paced,55,59.1%,96.5%,52.7% 63.6%,5.5% 5.5%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,The Tech Academy,Online,Software Developer BootCamp,1/1/2021 6/30/2021,Self-paced,55,59.1%,96.5%,52.7% 63.6%,5.5% 5.5%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Juno College of Technology,Toronto,Data Analytics Bootcamp,7/1/2021 12/31/2021,77,26,100.0%,96.3%,26.9% 57.7%,7.7% 11.5%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,The Tech Academy,Online,Front-End Web Developernan,7/1/2021 12/31/2021,Self-paced,9,86.7%,100.0%,77.8% 88.9%,0.0% 0.0%,...,NaN,20.0% 16.7%,20.0% 33.3%,0.0% 0.0%,NaN,NaN,NaN,NaN,NaN,NaN
50,The Tech Academy,Online,C# and .NET Boot Camp,7/1/2021 12/31/2021,Self-paced,13,88.5%,100.0%,69.2% 69.2%,7.7% 7.7%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Codesmith,Part Time Remote Immersive,Full-Stack Web Development,7/1/2021 12/31/2021,270,40,93.5%,93.0%,60.0% 87.5%,0.0% 0.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Tech Elevator,Wilmington,Full-Stack Software Development,7/1/2021 12/31/2021,95,7,70.0%,100.0%,28.5% 42.8%,28.6% 28.6%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
final['1. Employed in-field']

0      55.6% 66.7%
1     66.7% 100.0%
2      64.3% 76.2%
3      50.0% 92.9%
4      62.5% 81.3%
5      66.7% 90.4%
6      78.6% 88.1%
7      43.8% 81.3%
8      46.7% 60.0%
9      48.1% 85.3%
10     61.0% 89.8%
11     74.2% 83.9%
12     85.3% 94.0%
13     58.0% 81.5%
14     36.8% 63.2%
15     87.5% 93.7%
16     58.3% 83.3%
17     40.0% 80.9%
18     63.8% 86.2%
19     58.8% 70.6%
20     37.1% 70.1%
21     50.0% 63.0%
22     57.1% 78.6%
23     51.2% 89.4%
24     50.0% 50.0%
25     66.7% 89.2%
26     93.2% 94.5%
27     85.1% 93.6%
28     52.5% 72.5%
29     59.1% 84.8%
30     50.0% 75.0%
31     64.8% 76.5%
32     58.8% 82.4%
33     64.2% 84.9%
34     64.3% 92.9%
35     63.9% 86.1%
36     84.0% 91.0%
37     46.8% 82.3%
38     55.4% 78.6%
39     52.7% 83.5%
40     56.3% 68.8%
41     51.5% 60.6%
42     70.8% 87.5%
43     69.6% 91.3%
44     72.3% 84.6%
45     59.3% 79.7%
46     52.7% 63.6%
47     52.7% 63.6%
48     26.9% 57.7%
49     77.8% 88.9%
50     69.2% 69.2%
51     60.0% 87.5%
52     28.5% 42.8%
Name: 1. Employed in-field, dtype: object

In [28]:
final = final.applymap(lambda x: x.strip() if isinstance(x, str) else x)

In [29]:
final_2 = final

In [30]:
cols_to_split = ['1. Employed in-field',
       '2. Not seeking in-field employment', '3. Still seeking a job in-field',
       'Median Annual Base Salary',
       'Under $60,000',
       '$60,000-$70,000', '$70,000-$80,000', '$80,000-$90,000',
       '$90,000-$100,000', 'Over $100,000','Under $80,000', '$100,000-$110,000', '$110,000-$120,000',
       'Over $120,000','Under $50,000',
       '$50,000-$60,000', 'Over $90,000', 'Under $70,000', 'Over $110,000',
       'Under $110,000', '$120,000-$130,000', '$130,000-$140,000',
       '$140,000-$150,000', 'Over $150,000', 'Under $40,000',
       '$40,000-$50,000', 'Over $80,000', '$60,000-70,000',
       '$70,000-80,000', '$80,000-90,000', 'Under $120,000',
       '$150,000-$160,000', 'Over $160,000', 'Under $30,000',
       '$30,000-$40,000', 'Over $70,000','Under $100,000', 'Over $140,000']

In [31]:
for col in cols_to_split:
    new_cols = final_2[col].str.split(' ', expand=True)

# Rename the new columns to include the original column name and suffixes
    new_cols = new_cols.rename(columns={0: f"{col}_90days", 1: f"{col}_180days"})

# Add the new columns to the original dataframe with the modified column names, drop original
    final_2 = pd.concat([final_2, new_cols], axis=1).drop(col, axis=1)

In [32]:
final_2

,School Name,Campus Location,Program Name,Reporting Period,"Published Course Length (in days, including weekends and holidays)",Graduates Included in Report,Graduation Rate,How many students intended to seek in-field employment within 180 days of graduating?,How many students intended to seek in-field employment within 180 days of graduating,1. Employed in-field_90days,...,"Under $30,000_90days","Under $30,000_180days","$30,000-$40,000_90days","$30,000-$40,000_180days","Over $70,000_90days","Over $70,000_180days","Under $100,000_90days","Under $100,000_180days","Over $140,000_90days","Over $140,000_180days"
0,The Tech Academy,Online,Python Developer Boot Camp,7/1/2021 12/31/2021,Self-paced,9,82.4%,90.0%,NaN,55.6%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,The Tech Academy,Online,Data Science Boot Camp,1/1/2021 6/30/2021,Self-paced,3,100.0%,100.0%,NaN,66.7%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Turing School of Software and Design,Online,Back End Engineering,1/1/2021 6/30/2021,220,84,68.0%,100.0%,NaN,64.3%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Codeup,Dallas,Full-Stack Web Development,1/1/2021 6/30/2021,200,14,82.4%,100.0%,NaN,50.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Code Platoon,Chicago,Full-Stack Web Development,7/1/2021 12/31/2021,120,16,81.0%,94.1%,NaN,62.5%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Tech Elevator,Pittsburgh,Full-Stack Software Development,1/1/2021 6/30/2021,95,42,95.5%,100.0%,NaN,66.7%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Codeup,San Antonio,Data Science,7/1/2021 12/31/2021,200,42,85.7%,100.0%,NaN,78.6%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,"Codeup, LLC",San Antonio,Data Science,7/1/2020 12/21/2020,165,16,94.1%,100.0%,NaN,43.8%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Code Platoon,Chicago,Full-Stack Web Development,7/1/2020 12/31/2020,104,15,88.2%,93.3%,NaN,46.7%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Codesmith,Los Angeles,Full-Stack Web Development,1/1/2021 6/30/2021,100,130,94.8%,99.2%,NaN,48.1%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Tech Elevator,National Live Remote,Full-Stack Software Development,1/1/2021 6/30/2021,95,59,88.1%,79.7%,NaN,61.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Tech Elevator,Cleveland,Full-Stack Software Development,1/1/2021 6/30/2021,95,31,94.7%,86.1%,NaN,74.2%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Tech Elevator,Columbus,Full-Stack Software Development,7/1/2021 12/31/2021,95,116,95.2%,98.3%,NaN,85.3%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Codeup,San Antonio,Full-Stack Web Development,7/1/2021 12/31/2021,200,81,86.2%,100.0%,NaN,58.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,"Codeup, LLC",San Antonio,Full-Stack Web Development\r- Java -,7/1/2020 12/31/2020,170,38,80.9%,100.0%,NaN,36.8%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Tech Elevator,Cincinnati,Full-Stack Software Development,7/1/2021 12/31/2021,95,64,95.5%,100.0%,NaN,87.5%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Code Platoon,Chicago,Full-Stack Web Development,7/1/2021 12/31/2021,220,12,85.7%,100.0%,NaN,58.3%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Codesmith,West Coast Remote,Full-Stack Web Development,7/1/2021 12/31/2021,100,110,91.9%,94.0%,NaN,40.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Tech Elevator,Philadelphia,Full-Stack Software Development,7/1/2021 12/31/2021,95,58,93.5%,100.0%,NaN,63.8%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Turing School of Software and Design,Online,Front End Engineering,1/1/2021 6/30/2021,220,85,72.3%,100.0%,NaN,58.8%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Juno College of Technology,Toronto,Web Development Immersive,7/1/2021 12/31/2021,77,110,95.8%,99.0%,NaN,37.1%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,The Tech Academy,Online,Software Developer Bootnan,7/1/2021 12/31/2021,Self-paced,46,61.5%,95.8%,NaN,50.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,The Tech Academy,Online,Boot Camp,1/1/2021 6/30/2021,Self-paced,14,90.9%,93.3%,NaN,57.1%,...,33.3%,33.3%,33.3%,33.3%,0.0%,0.0%,NaN,NaN,NaN,NaN
23,Codesmith,New York,Full-Stack Web Development,1/1/2021 6/30/2021,100,123,94.7%,96.9%,NaN,51.2%,...,NaN,NaN,NaN,NaN,NaN,NaN,15.9%,12.3%,19.0%,17.9%
24,The Tech Academy,"Salt Lake City, Utah",Software Developer Bootcamp,7/1/2020 12/31/2020,Self-paced,10,90.9%,100.0%,NaN,50.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Tech Elevator,National Live Remote,Full-Stack Software Development,7/1/2021 12/31/2021,95,93,88.6%,100.0%,NaN,66.7%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Tech Elevator,Cleveland,Full-Stack Software Development,7/1/2021 12/31/2021,95,73,96.7%,83.0%,NaN,93.2%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Tech Elevator,Columbus,Full-Stack Software Development,1/1/2021 6/30/2021,95,47,96.3%,90.4%,NaN,85.1%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Code Chrysalis,"Tokyo, Japan",The Immersive Bootcamp,7/1/2020 12/31/2020,84,40,93.0%,88.9%,NaN,52.5%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Codeup,San Antonio - Vogue,Full-Stack Web Development,1/1/2021 6/30/2021,200,66,75.0%,100.0%,NaN,59.1%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,"Codeup, LLC",Dallas,Full-Stack Web Development-Java,7/1/2020 12/21/2020,170,17,100.0%,100.0%,NaN,50.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Tech Elevator,Cincinnati,Full-Stack Software Development,1/1/2021 6/30/2021,95,34,89.7%,97.1%,NaN,64.8%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Codeup,Dallas,Full-Stack Web Development,7/1/2021 12/31/2021,200,17,89.5%,100.0%,NaN,58.8%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Code Platoon,Chicago,Full-Stack Web Development,1/1/2021 6/30/2021,120,55,91.8%,98.2%,NaN,64.2%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Launch Academy,Boston,Fundamentals of Web Development,7/1/2021 12/31/2021,90,15,57.7%,93.3%,NaN,64.3%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Codeup,San Antonio - Vogue,Data Science,1/1/2021 6/30/2021,200,36,94.7%,100.0%,NaN,63.9%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Tech Elevator,Pittsburgh,Full-Stack Software Development,7/1/2021 12/31/2021,95,100,95.2%,100.0%,NaN,84.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Codesmith,Central Remote Immersive,Full-Stack Web Development,7/1/2021 12/31/2021,100,62,95.7%,93.9%,NaN,46.8%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Turing School of Software and Design,Online,Back End Engineering,7/1/2021 12/31/2021,220,47,48.1%,100.0%,NaN,55.4%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Codesmith,East Coast Remote,Full-Stack Web Development,7/1/2021 12/31/2021,100,91,92.8%,NaN,96.8%,52.7%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,The Tech Academy,Online,Python Developer Boot Camp,1/1/2021 6/30/2021,Self-paced,16,78.3%,100.0%,NaN,56.3%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,The Tech Academy,Online,C# and .NET Boot Camp,1/1/2021 6/30/2021,Self-paced,33,57.1%,97.1%,NaN,51.5%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Codesmith,Remote,Part-Time Full-Stack Web\rDevelopment,1/1/2021 6/30/2021,270,25,100.0%,89.3%,NaN,70.8%,...,NaN,NaN,NaN,NaN,NaN,NaN,14.3%,19.0%,28.6%,23.8%
43,Tech Elevator,Philadelphia,Full-Stack Software Development,1/1/2021 6/30/2021,95,23,88.5%,100.0%,NaN,69.6%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Turing School of Software and Design,Online,Front End Engineering,7/1/2021 12/31/2021,220,59,74.4%,100.0%,NaN,72.3%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Juno College of Technology,Toronto,Web Development Immersive,1/1/2021 6/30/2021,77,123,94.0%,100.0%,NaN,59.3%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,The Tech Academy,Online,Software Developer BootCamp,1/1/2021 6/30/2021,Self-paced,55,59.1%,96.5%,NaN,52.7%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,The Tech Academy,Online,Software Developer BootCamp,1/1/2021 6/30/2021,Self-paced,55,59.1%,96.5%,NaN,52.7%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Juno College of Technology,Toronto,Data Analytics Bootcamp,7/1/2021 12/31/2021,77,26,100.0%,96.3%,NaN,26.9%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,The Tech Academy,Online,Front-End Web Developernan,7/1/2021 12/31/2021,Self-paced,9,86.7%,100.0%,NaN,77.8%,...,20.0%,16.7%,20.0%,33.3%,0.0%,0.0%,NaN,NaN,NaN,NaN
50,The Tech Academy,Online,C# and .NET Boot Camp,7/1/2021 12/31/2021,Self-paced,13,88.5%,100.0%,NaN,69.2%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Codesmith,Part Time Remote Immersive,Full-Stack Web Development,7/1/2021 12/31/2021,270,40,93.5%,93.0%,NaN,60.0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Tech Elevator,Wilmington,Full-Stack Software Development,7/1/2021 12/31/2021,95,7,70.0%,100.0%,NaN,28.5%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
final_2['How many students intended to seek in-field employment within 180 days of graduating?'] = final_2['How many students intended to seek in-field employment within 180 days of graduating?'].fillna('')  + final_2['How many students intended to seek in-field employment within 180 days of graduating'].fillna('')
final_2.drop('How many students intended to seek in-field employment within 180 days of graduating', inplace=True, axis=1)

In [34]:
under70_90d = ['Under $30,000_90days', '$30,000-$40,000_90days','Under $50,000_90days','Under $60,000_90days','$60,000-$70,000_90days','Under $40,000_90days','Under $70,000_90days','$50,000-$60,000_90days','$40,000-$50,000_90days','$60,000-70,000_90days']
under70_180d = ['Under $30,000_180days', '$30,000-$40,000_180days','Under $50,000_180days','Under $60,000_180days','$60,000-$70,000_180days','Under $40,000_180days', 'Under $70,000_180days','$50,000-$60,000_180days','$40,000-$50,000_180days','$60,000-70,000_180days']
r70_80k90d = ['$70,000-$80,000_90days','$70,000-80,000_90days','Over $70,000_90days', 'Under $80,000_90days']
r70_80k180d = ['$70,000-$80,000_180days','$70,000-80,000_180days','Over $70,000_180days','Under $80,000_180days']
r80_90k90d = ['$80,000-$90,000_90days','$80,000-90,000_90days','Over $80,000_90days']
r80_90k180d = ['$80,000-$90,000_180days','$80,000-90,000_180days','Over $80,000_180days']
over9090 = ['$90,000-$100,000_90days','Over $100,000_90days','$100,000-$110,000_90days','Over $160,000_90days','Over $120,000_90days','$150,000-$160,000_90days','Under $120,000_90days','$110,000-$120,000_90days','Over $90,000_90days','Over $110,000_90days','Under $110,000_90days','$120,000-$130,000_90days','$130,000-$140,000_90days','$140,000-$150,000_90days','Over $150,000_90days','Under $100,000_90days', 'Over $140,000_90days']
over90180 = ['$90,000-$100,000_180days', 'Over $100,000_180days',
       '$100,000-$110,000_180days', '$110,000-$120,000_180days',
       'Over $120,000_180days', 'Over $90,000_180days',
       'Over $110,000_180days', 'Under $110,000_180days',
       '$120,000-$130,000_180days', '$130,000-$140,000_180days',
       '$140,000-$150,000_180days', 'Over $150,000_180days',
        'Under $120,000_180days',
       '$150,000-$160,000_180days', 'Over $160,000_180days','Under $100,000_180days', 'Over $140,000_180days',]

In [35]:
final_2[under70_90d] = final_2[under70_90d].apply(lambda x: x.str.rstrip('%').astype('float') / 100)
final_2['under70K90d'] = final_2[under70_90d].sum(axis=1)
final_2['under70K90d'] = (final_2['under70K90d'] * 100).round(1).astype(str) + '%'
# Drop the specific columns
final_2.drop(under70_90d, axis=1, inplace=True)

In [36]:
final_2[under70_180d] = final_2[under70_180d].apply(lambda x: x.str.rstrip('%').astype('float') / 100)
final_2['under70K180d'] = final_2[under70_180d].sum(axis=1)
final_2['under70K180d'] = (final_2['under70K180d'] * 100).round(1).astype(str) + '%'
# Drop the specific columns
final_2.drop(under70_180d, axis=1, inplace=True)

In [37]:
final_2[r70_80k90d] = final_2[r70_80k90d].apply(lambda x: x.str.rstrip('%').astype('float') / 100)
final_2['70K_80K90d'] = final_2[r70_80k90d].sum(axis=1)
final_2['70K_80K90d'] = (final_2['70K_80K90d'] * 100).round(1).astype(str) + '%'
# Drop the specific columns
final_2.drop(r70_80k90d, axis=1, inplace=True)

In [38]:
final_2[r70_80k180d] = final_2[r70_80k180d].apply(lambda x: x.str.rstrip('%').astype('float') / 100)
final_2['70K_80K180d'] = final_2[r70_80k180d].sum(axis=1)
final_2['70K_80K180d'] = (final_2['70K_80K180d'] * 100).round(1).astype(str) + '%'
# Drop the specific columns
final_2.drop(r70_80k180d, axis=1, inplace=True)

In [39]:
final_2[r80_90k90d] = final_2[r80_90k90d].apply(lambda x: x.str.rstrip('%').astype('float') / 100)
final_2['80K_90K90d'] = final_2[r80_90k90d].sum(axis=1)
final_2['80K_90K90d'] = (final_2['80K_90K90d'] * 100).round(1).astype(str) + '%'
# Drop the specific columns
final_2.drop(r80_90k90d, axis=1, inplace=True)

In [40]:
final_2[r80_90k180d] = final_2[r80_90k180d].apply(lambda x: x.str.rstrip('%').astype('float') / 100)
final_2['80K_90K180d'] = final_2[r80_90k180d].sum(axis=1)
final_2['80K_90K180d'] = (final_2['80K_90K180d'] * 100).round(1).astype(str) + '%'
# Drop the specific columns
final_2.drop(r80_90k180d, axis=1, inplace=True)

In [41]:
final_2[over9090] = final_2[over9090].apply(lambda x: x.str.rstrip('%').astype('float') / 100)
final_2['over90K90d'] = final_2[over9090].sum(axis=1)
final_2['over90K90d'] = (final_2['over90K90d'] * 100).round(1).astype(str) + '%'
# Drop the specific columns
final_2.drop(over9090, axis=1, inplace=True)

In [42]:
final_2[over90180] = final_2[over90180].apply(lambda x: x.str.rstrip('%').astype('float') / 100)
final_2['over90K180d'] = final_2[over90180].sum(axis=1)
final_2['over90K180d'] = (final_2['over90K180d'] * 100).round(1).astype(str) + '%'
# Drop the specific columns
final_2.drop(over90180, axis=1, inplace=True)

In [43]:
final_2.columns

Index(['School Name', 'Campus Location', 'Program Name', 'Reporting Period',
       'Published Course Length (in days, including weekends and holidays)',
       'Graduates Included in Report', 'Graduation Rate',
       'How many students intended to seek in-field employment within 180 days of graduating?',
       '1. Employed in-field_90days', '1. Employed in-field_180days',
       '2. Not seeking in-field employment_90days',
       '2. Not seeking in-field employment_180days',
       '3. Still seeking a job in-field_90days',
       '3. Still seeking a job in-field_180days',
       'Median Annual Base Salary_90days', 'Median Annual Base Salary_180days',
       'under70K90d', 'under70K180d', '70K_80K90d', '70K_80K180d',
       '80K_90K90d', '80K_90K180d', 'over90K90d', 'over90K180d'],
      dtype='object')

In [44]:
final_2[['reporting_start', 'reporting_end']] = final_2['Reporting Period'].str.split(' ', expand=True)
final_2.drop('Reporting Period', axis=1, inplace=True)

In [45]:
final_2.columns

Index(['School Name', 'Campus Location', 'Program Name',
       'Published Course Length (in days, including weekends and holidays)',
       'Graduates Included in Report', 'Graduation Rate',
       'How many students intended to seek in-field employment within 180 days of graduating?',
       '1. Employed in-field_90days', '1. Employed in-field_180days',
       '2. Not seeking in-field employment_90days',
       '2. Not seeking in-field employment_180days',
       '3. Still seeking a job in-field_90days',
       '3. Still seeking a job in-field_180days',
       'Median Annual Base Salary_90days', 'Median Annual Base Salary_180days',
       'under70K90d', 'under70K180d', '70K_80K90d', '70K_80K180d',
       '80K_90K90d', '80K_90K180d', 'over90K90d', 'over90K180d',
       'reporting_start', 'reporting_end'],
      dtype='object')

In [46]:
final_2.rename(columns={'School Name': 'school_name',
                    'Campus Location': 'campus_location',
                    'Program Name': 'program_name',
                    'Published Course Length (in days, including weekends and holidays)':'course_length',
                    'Graduates Included in Report':'graduates_included',
                    'Graduation Rate':'graduated_ontime',
                    'How many students intended to seek in-field employment within 180 days of graduating?': 'intend_infield_employment',
                    '1. Employed in-field_90days': 'employed_infield_90days', 
                    '1. Employed in-field_180days':'employed_infield_180days',
                    '2. Not seeking in-field employment_90days':'not_seeking_infield_90days',
                    '2. Not seeking in-field employment_180days':'not_seeking_infield_180days',
                    '3. Still seeking a job in-field_90days':'still_seeking_infield_90days',
                    '3. Still seeking a job in-field_180days':'still_seeking_infield_180days',
                    'Median Annual Base Salary_90days':'median_annual_salary90days',
                    'Median Annual Base Salary_180days':'median_annual_salary180days',
                    'under70K90d':'under70K_90days','under70K180d':'under70K_180days', 
                    '70K_80K90d': 'salary_70K_80K_90days', '70K_80K180d' : 'salary_70K_80K_180days',
                    '80K_90K90d' : 'salary_80K_90K_90days','80K_90K180d' : 'salary_80K_90K_180days',
                    'over90K90d' : 'over90K_90days', 'over90K180d' : 'over90K_180days'
                    }, inplace=True)

In [48]:
final_2['program_name'] = final_2['program_name'].str.replace(r'\r',' ', regex=True)

In [49]:
cols = ['school_name',
        'campus_location',
        'program_name',
        'reporting_start', 
        'reporting_end', 
        'course_length',
        'graduates_included',
        'graduated_ontime',
        'intend_infield_employment',
        'employed_infield_90days',
        'employed_infield_180days',
        'not_seeking_infield_90days',
        'not_seeking_infield_180days',
        'still_seeking_infield_90days',
        'still_seeking_infield_180days',
        'median_annual_salary90days',
        'median_annual_salary180days',
        'under70K_90days',
        'under70K_180days',
        'salary_70K_80K_90days',
        'salary_70K_80K_180days',
        'salary_80K_90K_90days',
        'salary_80K_90K_180days',
        'over90K_90days',
        'over90K_180days']

In [50]:
final_2 = final_2.reindex(columns=cols)

In [51]:
final_2.to_csv('data/complete_53.csv',index=False)